layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: true
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: lohmankevin
  # mastodon: your_username
  medium: badpirate
  stackoverflow: 285694/badpirate?tab=profile
  # telegram: your_username
  twitter: badpirate
  resume: http://kevin.lohman.me
  # unsplash: your_username
  # vk: your_username
  # website: https://kevin.lohman.me
  # youtube: your_username

active:
  - name: Apple
    web_url: https://www.apple.com
    image_url: assets/apple.png
  - name: Windfall
    web_url: https://windfall.badpirate.net
    image_url: assets/windfall.png

past:
  - name: UnifyID iOS SDK
    web_url: https://developer.unify.id/docs/ios_sdk
    image_url: assets/unifyid.svg
  - name: Facebook
    web_url: https://www.facebook.com
    image_url: assets/fb.png
  - name: Blackberry
    web_url: https://apps.apple.com/us/app/blackberry-work/id890656632
    image_url: assets/bbwork.png
  - name: US Navy, ET2
    web_url: https://en.wikipedia.org/wiki/Lockheed_P-3_Orion
    image_url: assets/lickme.png